name: Build and deploy jekyll site

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v2

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # can change this to 2.7 or whatever version you prefer

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true
          prettier_opts: '{ "useTabs": true, "printWidth": 1000 }'
          
      - name: generate short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: create PDF directory
        run: mkdir ./_site/pdf
      
      - name: create pdf of web page
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./_site/index.html
          outputFile: ./_site/pdf/CianYongLeow_CV_${{ steps.vars.outputs.sha_short }}.pdf
          pdfOptions: '{"format": "A4"}'

      - name: add pdf link to page
        run: sed -i "s|#pdf|pdf/CianYongLeow_CV_${{ steps.vars.outputs.sha_short }}.pdf|g" ./_site/index.html

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          exclude_assets: '.github,certifications/**/**.html,coding-projects/**/**.html,education/**/**.html,employment/**/**.html'
